name: Generate ASCII Network

on: push
jobs:
  generate-ascii:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Install Cowsay CMD
          run: sudo apt-get install cowsay -y

        - name: Execute CMD
          run: cowsay -f cow "Run for cover, I am a cow....www" >> cow.txt

        - name: Test File Exists
          run: grep i "cow" cow.txt

        - name: Read File
          run: cat cow.txt

        - name: Checkout Repo files
          run: ls