name: Generate ASCII Network

on: push
jobs:
  generate-ascii:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Executing Shell Script
          run: |
            chmod +x ascii-script.sh
            ./ascii-script.sh